<notification_data>
	<fines_fees_list>
		<user_fines_fees>
			<create_date>26/06/2016</create_date>
			<entity_action/>
			<fine_comment/>
			<fine_fee_ammount>
				<currency>NOK</currency>
				<sum>600.00</sum>
				<vat>0.00</vat>
			</fine_fee_ammount>
			<fine_fee_type>LOSTITEMREPLACEMENTFEE</fine_fee_type>
			<fine_fee_type_display>Erstatningsgebyr ved tap</fine_fee_type_display>
			<fine_owner>
				<address>
					<city>Oslo</city>
					<country>NOR</country>
					<country_display>Norge</country_display>
					<create_date>02/06/2015</create_date>
					<entity_action/>
					<library_id/>
					<library_unit_id/>
					<line1>Nydalsveien 37</line1>
					<line2/>
					<line3/>
					<line4/>
					<line5/>
					<note/>
					<originating_id/>
					<postal_code>NO-0484</postal_code>
					<preferred>true</preferred>
					<segment_types_display>
						<string>Låntakerkommunikasjon</string>
					</segment_types_display>
					<state_province/>
					<user_address_types_display/>
				</address>
				<automatic_creation>true</automatic_creation>
				<automatically_activate_locate_profile>true</automatically_activate_locate_profile>
				<automatically_locate_resource>true</automatically_locate_resource>
				<bibliographic_titles/>
				<cancel_request_on_locate_failure>false</cancel_request_on_locate_failure>
				<code>1032105</code>
				<code_rfid/>
				<create_date>02/06/2015</create_date>
				<default_acq_loctaion_id>259506500002215</default_acq_loctaion_id>
				<default_item_loctaion_id>259508540002215</default_item_loctaion_id>
				<default_move_loctaion_id>259508540002215</default_move_loctaion_id>
				<default_pickup_loctaion_id>259501520002215</default_pickup_loctaion_id>
				<description>Handelshøyskolen BI – campus Oslo, Hovedbiblioteket</description>
				<digital_objects/>
				<digital_storage_size/>
				<edi_code/>
				<edi_type/>
				<email>
					<create_date>04/11/2015</create_date>
					<description/>
					<email>biblioteket@bi.no</email>
					<entity_action/>
					<external_id/>
					<library_id/>
					<library_unit_id/>
					<originating_id/>
					<preferred>true</preferred>
				</email>
				<entity_action/>
				<ignore_electronic>false</ignore_electronic>
				<itemless_library/>
				<leader_institution_id/>
				<library_id>259501520002215</library_id>
				<library_unit_id/>
				<name>Handelshøyskolen BI – campus Oslo, Hovedbiblioteket</name>
				<named_users/>
				<org_scope>
					<customer_id>2200</customer_id>
					<institution_id>2215</institution_id>
					<library_id>259501520002215</library_id>
					<library_unit_id/>
				</org_scope>
				<organization_id>259501520002215</organization_id>
				<organization_path>2200.2215.259501520002215</organization_path>
				<organization_type>LIBRARY</organization_type>
				<parent_org_id>2215</parent_org_id>
				<path>47BIBSYS.47BIBSYS_BI.1032105</path>
				<phone>
					<create_date>02/06/2015</create_date>
					<entity_action/>
					<external_id/>
					<library_id/>
					<library_unit_id/>
					<originating_id/>
					<phone>46410250</phone>
					<preferred>true</preferred>
					<preferred_phone/>
					<preferred_sms/>
				</phone>
				<premium_sandbox/>
				<reject_not_available_requestable>false</reject_not_available_requestable>
				<reject_on_locate_failure>false</reject_on_locate_failure>
				<reject_only_electronic>false</reject_only_electronic>
				<resource_sharing_library>true</resource_sharing_library>
				<serves_other_institutions>false</serves_other_institutions>
				<standard_sandbox/>
				<status>ACTIVE</status>
				<support_code/>
				<unique_ejournal_titles/>
				<url_mapping_prefix/>
			</fine_owner>
			<fines_fee_transactions/>
			<item_id/>
			<item_loan_id>1074112150002215</item_loan_id>
			<item_title>Strategi Øystein D. Fjeldstad og Randi Lunnan (red.)</item_title>
			<library_id>259501520002215</library_id>
			<library_unit_id/>
			<originating_item_id/>
			<originating_loan_id/>
			<owner>Handelshøyskolen BI – campus Oslo, Hovedbiblioteket</owner>
			<status_date/>
			<user_group>1</user_group>
			<user_statistics1/>
			<user_statistics10/>
			<user_statistics2/>
			<user_statistics3/>
			<user_statistics4/>
			<user_statistics5/>
			<user_statistics6/>
			<user_statistics7/>
			<user_statistics8/>
			<user_statistics9/>
		</user_fines_fees>
		<user_fines_fees>
			<create_date>26/06/2016</create_date>
			<entity_action/>
			<fine_comment>Date generated: 26/06/2016, Due: 10/06/2016, Fine Policy/ies:  Overdue fine policy: 10.00 overdue fine per open day , Action: Lost with overdue charge</fine_comment>
			<fine_fee_ammount>
				<currency>NOK</currency>
				<sum>120.00</sum>
				<vat>0.00</vat>
			</fine_fee_ammount>
			<fine_fee_type>OVERDUEFINE</fine_fee_type>
			<fine_fee_type_display>Forfallsgebyr</fine_fee_type_display>
			<fine_owner>
				<address>
					<city>Oslo</city>
					<country>NOR</country>
					<country_display>Norge</country_display>
					<create_date>02/06/2015</create_date>
					<entity_action/>
					<library_id/>
					<library_unit_id/>
					<line1>Nydalsveien 37</line1>
					<line2/>
					<line3/>
					<line4/>
					<line5/>
					<note/>
					<originating_id/>
					<postal_code>NO-0484</postal_code>
					<preferred>true</preferred>
					<segment_types_display>
						<string>Låntakerkommunikasjon</string>
					</segment_types_display>
					<state_province/>
					<user_address_types_display/>
				</address>
				<automatic_creation>true</automatic_creation>
				<automatically_activate_locate_profile>true</automatically_activate_locate_profile>
				<automatically_locate_resource>true</automatically_locate_resource>
				<bibliographic_titles/>
				<cancel_request_on_locate_failure>false</cancel_request_on_locate_failure>
				<code>1032105</code>
				<code_rfid/>
				<create_date>02/06/2015</create_date>
				<default_acq_loctaion_id>259506500002215</default_acq_loctaion_id>
				<default_item_loctaion_id>259508540002215</default_item_loctaion_id>
				<default_move_loctaion_id>259508540002215</default_move_loctaion_id>
				<default_pickup_loctaion_id>259501520002215</default_pickup_loctaion_id>
				<description>Handelshøyskolen BI – campus Oslo, Hovedbiblioteket</description>
				<digital_objects/>
				<digital_storage_size/>
				<edi_code/>
				<edi_type/>
				<email>
					<create_date>04/11/2015</create_date>
					<description/>
					<email>biblioteket@bi.no</email>
					<entity_action/>
					<external_id/>
					<library_id/>
					<library_unit_id/>
					<originating_id/>
					<preferred>true</preferred>
				</email>
				<entity_action/>
				<ignore_electronic>false</ignore_electronic>
				<itemless_library/>
				<leader_institution_id/>
				<library_id>259501520002215</library_id>
				<library_unit_id/>
				<name>Handelshøyskolen BI – campus Oslo, Hovedbiblioteket</name>
				<named_users/>
				<org_scope>
					<customer_id>2200</customer_id>
					<institution_id>2215</institution_id>
					<library_id>259501520002215</library_id>
					<library_unit_id/>
				</org_scope>
				<organization_id>259501520002215</organization_id>
				<organization_path>2200.2215.259501520002215</organization_path>
				<organization_type>LIBRARY</organization_type>
				<parent_org_id>2215</parent_org_id>
				<path>47BIBSYS.47BIBSYS_BI.1032105</path>
				<phone>
					<create_date>02/06/2015</create_date>
					<entity_action/>
					<external_id/>
					<library_id/>
					<library_unit_id/>
					<originating_id/>
					<phone>46410250</phone>
					<preferred>true</preferred>
					<preferred_phone/>
					<preferred_sms/>
				</phone>
				<premium_sandbox/>
				<reject_not_available_requestable>false</reject_not_available_requestable>
				<reject_on_locate_failure>false</reject_on_locate_failure>
				<reject_only_electronic>false</reject_only_electronic>
				<resource_sharing_library>true</resource_sharing_library>
				<serves_other_institutions>false</serves_other_institutions>
				<standard_sandbox/>
				<status>ACTIVE</status>
				<support_code/>
				<unique_ejournal_titles/>
				<url_mapping_prefix/>
			</fine_owner>
			<fines_fee_transactions/>
			<item_id/>
			<item_loan_id>1074112150002215</item_loan_id>
			<item_title>Strategi Øystein D. Fjeldstad og Randi Lunnan (red.)</item_title>
			<library_id>259501520002215</library_id>
			<library_unit_id/>
			<originating_item_id/>
			<originating_loan_id/>
			<owner>Handelshøyskolen BI – campus Oslo, Hovedbiblioteket</owner>
			<status_date/>
			<user_group>1</user_group>
			<user_statistics1/>
			<user_statistics10/>
			<user_statistics2/>
			<user_statistics3/>
			<user_statistics4/>
			<user_statistics5/>
			<user_statistics6/>
			<user_statistics7/>
			<user_statistics8/>
			<user_statistics9/>
		</user_fines_fees>
	</fines_fees_list>
	<general_data>
		<address_from>noreply@bi.no</address_from>
		<current_date>26/06/2016</current_date>
		<letter_channel_info/>
		<letter_name>Regning for tapt materiale</letter_name>
		<letter_type>FulLostLoanLetter</letter_type>
		<subject>Regning for tapt materiale fra biblioteket</subject>
	</general_data>
	<item_loan>
		<author>Fjeldstad, Øystein D.</author>
		<barcode>15tb02965</barcode>
		<booking_request_id/>
		<calculated_due_date/>
		<call_number>65.011.1 STR</call_number>
		<create_date>10/06/2016</create_date>
		<delivery_address/>
		<description/>
		<description_for_display>Call Number: 65.011.1 STR </description_for_display>
		<due_date>10/06/2016</due_date>
		<due_date_shortened_reason/>
		<due_date_start_calculation_date/>
		<entity_action/>
		<external_item_id/>
		<fine>720,00 NOK</fine>
		<fine_action>OVERDUE_LOST</fine_action>
		<from_another_inst/>
		<from_another_inst_circ_desk/>
		<from_another_inst_library/>
		<from_fulfillment_configuration_util>false</from_fulfillment_configuration_util>
		<item_id>2316945900002215</item_id>
		<item_loan_change_list/>
		<item_location_lib_id>259501520002215</item_location_lib_id>
		<job_title/>
		<library_id>259501520002215</library_id>
		<library_name>Handelshøyskolen BI – campus Oslo, Hovedbiblioteket</library_name>
		<library_unit_id/>
		<loan_circ_desk_id>259501540002215</loan_circ_desk_id>
		<loan_circ_desk_institution_code/>
		<loan_date>10/06/2016</loan_date>
		<loan_note/>
		<loan_status>Active</loan_status>
		<location_code>tb0031</location_code>
		<location_name>BIOSL Pensum</location_name>
		<material_type>BOOK</material_type>
		<middle_id>2216945720002215</middle_id>
		<mms_id>991419072404702215</mms_id>
		<need_to_create_user_demerit>true</need_to_create_user_demerit>
		<new_due_date_str>10/06/2016 21:00:00 CEST</new_due_date_str>
		<next_step/>
		<normalized_barcode>15tb02965</normalized_barcode>
		<notified_by_profiles>Purrebrev dagslån, dagen etter forfall;Purrebrev dagslån, 3 dager etter forfall;Purrebrev vanlige lån 7. dag;</notified_by_profiles>
		<old_due_date/>
		<old_due_date_str/>
		<originating_system_id/>
		<originating_user_id/>
		<physical_item/>
		<policy_list/>
		<process_status>LOST</process_status>
		<process_status_circ_desk/>
		<process_status_creator/>
		<publication_year/>
		<reading_room_status>NO_AT_RR</reading_room_status>
		<record_type>PUBLIC</record_type>
		<resource_sharing_operation>false</resource_sharing_operation>
		<return_circ_desk_id/>
		<return_date/>
		<return_date_str/>
		<returned_by/>
		<shortened_due_date_reason/>
		<title>Strategi Øystein D. Fjeldstad og Randi Lunnan (red.)</title>
		<user_expired>false</user_expired>
		<user_group>1</user_group>
		<user_id>702622300002215</user_id>
		<user_name/>
		<user_statistics1/>
		<user_statistics10/>
		<user_statistics2/>
		<user_statistics3/>
		<user_statistics4/>
		<user_statistics5/>
		<user_statistics6/>
		<user_statistics7/>
		<user_statistics8/>
		<user_statistics9/>
		<user_type>INTEXTAUTH</user_type>
		<version>4</version>
	</item_loan>
	<languages>
		<string>no</string>
		<string>en</string>
	</languages>
	<letter_params/>
	<letter_texts/>
	<loans_by_library/>
	<organization_unit>
		<address>
			<city>Oslo</city>
			<country>NOR</country>
			<country_display>Norge</country_display>
			<create_date>02/06/2015</create_date>
			<entity_action/>
			<library_id/>
			<library_unit_id/>
			<line1>Nydalsveien 37</line1>
			<line2/>
			<line3/>
			<line4/>
			<line5/>
			<note/>
			<originating_id/>
			<postal_code>NO-0484</postal_code>
			<preferred>true</preferred>
			<segment_types_display>
				<string>Låntakerkommunikasjon</string>
			</segment_types_display>
			<state_province/>
			<user_address_types_display/>
		</address>
		<automatic_creation>true</automatic_creation>
		<automatically_activate_locate_profile>true</automatically_activate_locate_profile>
		<automatically_locate_resource>true</automatically_locate_resource>
		<bibliographic_titles/>
		<cancel_request_on_locate_failure>false</cancel_request_on_locate_failure>
		<code>1032105</code>
		<code_rfid/>
		<create_date>02/06/2015</create_date>
		<default_acq_loctaion_id>259506500002215</default_acq_loctaion_id>
		<default_item_loctaion_id>259508540002215</default_item_loctaion_id>
		<default_move_loctaion_id>259508540002215</default_move_loctaion_id>
		<default_pickup_loctaion_id>259501520002215</default_pickup_loctaion_id>
		<description>Handelshøyskolen BI – campus Oslo, Hovedbiblioteket</description>
		<digital_objects/>
		<digital_storage_size/>
		<edi_code/>
		<edi_type/>
		<email>
			<create_date>04/11/2015</create_date>
			<description/>
			<email>biblioteket@bi.no</email>
			<entity_action/>
			<external_id/>
			<library_id/>
			<library_unit_id/>
			<originating_id/>
			<preferred>true</preferred>
		</email>
		<entity_action/>
		<ignore_electronic>false</ignore_electronic>
		<itemless_library/>
		<leader_institution_id/>
		<library_id>259501520002215</library_id>
		<library_unit_id/>
		<name>Handelshøyskolen BI – campus Oslo, Hovedbiblioteket</name>
		<named_users/>
		<org_scope>
			<customer_id>2200</customer_id>
			<institution_id>2215</institution_id>
			<library_id>259501520002215</library_id>
			<library_unit_id/>
		</org_scope>
		<organization_id>259501520002215</organization_id>
		<organization_path>2200.2215.259501520002215</organization_path>
		<organization_type>LIBRARY</organization_type>
		<parent_org_id>2215</parent_org_id>
		<path>47BIBSYS.47BIBSYS_BI.1032105</path>
		<phone>
			<create_date>02/06/2015</create_date>
			<entity_action/>
			<external_id/>
			<library_id/>
			<library_unit_id/>
			<originating_id/>
			<phone>46410250</phone>
			<preferred>true</preferred>
			<preferred_phone/>
			<preferred_sms/>
		</phone>
		<premium_sandbox/>
		<reject_not_available_requestable>false</reject_not_available_requestable>
		<reject_on_locate_failure>false</reject_on_locate_failure>
		<reject_only_electronic>false</reject_only_electronic>
		<resource_sharing_library>true</resource_sharing_library>
		<serves_other_institutions>false</serves_other_institutions>
		<standard_sandbox/>
		<status>ACTIVE</status>
		<support_code/>
		<unique_ejournal_titles/>
		<url_mapping_prefix/>
	</organization_unit>
	<phys_item_display>
		<accession_number/>
		<alt_call_number_type/>
		<attachments/>
		<author>Fjeldstad, Øystein D.</author>
		<available_items>
			<available_item>
				<barcode>15tb02965</barcode>
				<call_number>65.011.1 STR</call_number>
				<item_policy>3</item_policy>
				<library_code>1032105</library_code>
				<library_name>Handelshøyskolen BI – campus Oslo, Hovedbiblioteket</library_name>
				<location_code>tb0031</location_code>
				<location_name>BIOSL Pensum</location_name>
				<material_type>BOOK</material_type>
				<public_note/>
				<shelving_location/>
			</available_item>
		</available_items>
		<barcode>15tb02965</barcode>
		<call_number>65.011.1 STR</call_number>
		<call_number_type>8</call_number_type>
		<chron_i/>
		<chron_j/>
		<chron_k/>
		<chron_l/>
		<chron_m/>
		<copy_id/>
		<destination_name/>
		<display_alt_call_numbers/>
		<edition/>
		<enum_a/>
		<enum_b/>
		<enum_c/>
		<enum_d/>
		<enum_e/>
		<enum_f/>
		<enum_g/>
		<enum_h/>
		<fulfillment_note/>
		<imprint>Bergen Fagbokforl cop. 2014</imprint>
		<internal_note1>Status: tapt - tapt</internal_note1>
		<internal_note2>TIME FOR CIRC STATUS: 2015-11-12 | CIRC STATUS: 12</internal_note2>
		<internal_note3/>
		<inventory_material_type>Book</inventory_material_type>
		<isbn>9788245015409</isbn>
		<issn/>
		<issue_level_description/>
		<item_policy>Dagslån</item_policy>
		<library_code>1032105</library_code>
		<library_name>Handelshøyskolen BI – campus Oslo, Hovedbiblioteket</library_name>
		<location_code>tb0031</location_code>
		<location_name>BIOSL Pensum</location_name>
		<material_type>Book</material_type>
		<optional_barcodes>
			<string>15tb02965</string>
		</optional_barcodes>
		<owning_library_details>
			<address1>Nydalsveien 37</address1>
			<address2/>
			<address3/>
			<address4/>
			<address5/>
			<city>Oslo</city>
			<country>NOR</country>
			<email>biblioteket@bi.no</email>
			<identifiers>
				<code_value>
					<code>Primary Identifier</code>
					<value/>
				</code_value>
			</identifiers>
			<name>Handelshøyskolen BI – campus Oslo, Hovedbiblioteket</name>
			<phone>46410250</phone>
			<postal_code>NO-0484</postal_code>
			<state/>
			<title/>
			<user_group/>
			<user_title/>
		</owning_library_details>
		<owning_library_id>259501520002215</owning_library_id>
		<owning_library_name>Handelshøyskolen BI – campus Oslo, Hovedbiblioteket</owning_library_name>
		<parsed_alt_call_number/>
		<parsed_call_number/>
		<parsed_issue_level_description/>
		<permanent_library/>
		<permanent_location/>
		<profile_names/>
		<public_note/>
		<publication_date>cop. 2014</publication_date>
		<publication_place>Bergen</publication_place>
		<publisher>Fagbokforl</publisher>
		<row_call_number>$$h 65.011.1 STR </row_call_number>
		<shelving_location/>
		<statistics_note1/>
		<statistics_note2/>
		<statistics_note3/>
		<summary_holding_infos/>
		<title>Strategi</title>
		<title_abcnph>Strategi Øystein D. Fjeldstad og Randi Lunnan (red.)</title_abcnph>
	</phys_item_display>
	<receivers>
		<receiver>
			<address_types/>
			<attached_to_entity_id>702622300002215</attached_to_entity_id>
			<email_types/>
			<params/>
			<preferred_language>no</preferred_language>
			<receiver_id/>
			<receiver_type/>
			<receiver_type_class>com.exlibris.core.infra.model.HFrUser</receiver_type_class>
			<user_address>
				<city>Oslo</city>
				<country>NOR</country>
				<create_date>12/01/2016</create_date>
				<entity_action/>
				<library_id/>
				<library_unit_id/>
				<line1>Grefsenkollveien 12 B</line1>
				<line2/>
				<line3/>
				<line4/>
				<line5/>
				<note/>
				<originating_id/>
				<postal_code>0490</postal_code>
				<preferred>true</preferred>
				<state_province/>
			</user_address>
			<user_email>
				<create_date>12/01/2016</create_date>
				<description/>
				<email>fredrik.h.juell@bi.no</email>
				<entity_action/>
				<external_id/>
				<library_id/>
				<library_unit_id/>
				<originating_id/>
				<preferred>true</preferred>
			</user_email>
			<user_phone>
				<create_date>12/01/2016</create_date>
				<entity_action/>
				<external_id/>
				<library_id/>
				<library_unit_id/>
				<originating_id/>
				<phone>95961616</phone>
				<preferred>true</preferred>
				<preferred_phone/>
				<preferred_sms/>
			</user_phone>
			<user>
				<birth_date>01/01/1985</birth_date>
				<birth_date_dummy>
					<calendar>01/01/1985</calendar>
					<calendar_ui/>
					<day>1</day>
					<day_ui/>
					<default_value_for_with_validation>473436367090</default_value_for_with_validation>
					<full_date>1985-01-01</full_date>
					<input_date_tag_format>01.01.1985</input_date_tag_format>
					<month>0</month>
					<month_ui/>
					<date>false</date>
					<year>1985</year>
					<year_ui/>
				</birth_date_dummy>
				<campus_code>BIOSL</campus_code>
				<campus_code_original_value/>
				<cataloger_level>00</cataloger_level>
				<cataloger_level_original_value>00</cataloger_level_original_value>
				<checksum/>
				<create_date>12/01/2016</create_date>
				<default_language>no</default_language>
				<entity_action/>
				<expiry_date>15/02/2017</expiry_date>
				<expiry_date_dummy>
					<calendar>15/02/2017</calendar>
					<calendar_ui/>
					<day>15</day>
					<day_ui/>
					<default_value_for_with_validation>1487199599999</default_value_for_with_validation>
					<full_date>2017-02-15</full_date>
					<input_date_tag_format>15.02.2017</input_date_tag_format>
					<month>1</month>
					<month_ui/>
					<date>false</date>
					<year>2017</year>
					<year_ui/>
				</expiry_date_dummy>
				<external_id/>
				<failed_authentication>0</failed_authentication>
				<first_name>Gina</first_name>
				<force_password_change>false</force_password_change>
				<force_update_external>false</force_update_external>
				<force_update_external_original_fields>false</force_update_external_original_fields>
				<from_register_new_user>false</from_register_new_user>
				<gender/>
				<from_external_system>false</from_external_system>
				<job_description>TESTBRUKER for Fredrik H. Juell</job_description>
				<job_title/>
				<job_title_original_value/>
				<last_name>Tonic</last_name>
				<library_id/>
				<library_unit_id/>
				<linked_account>false</linked_account>
				<linking_id/>
				<locked_out>false</locked_out>
				<locked_out_date/>
				<login_restriction_exception/>
				<lti_course_code/>
				<middle_name/>
				<distributed>false</distributed>
				<original_id/>
				<password_expiry_date>10/07/2016</password_expiry_date>
				<pin_number/>
				<pin_number_original_value/>
				<product_name/>
				<purge_date/>
				<purge_date_dummy>
					<calendar>01/01/1970</calendar>
					<calendar_ui/>
					<day>1</day>
					<day_ui/>
					<default_value_for_with_validation>0</default_value_for_with_validation>
					<full_date/>
					<input_date_tag_format>00.00.0</input_date_tag_format>
					<month>0</month>
					<month_ui/>
					<date>true</date>
					<year>1970</year>
					<year_ui/>
				</purge_date_dummy>
				<record_type>PUBLIC</record_type>
				<registration_key/>
				<library_code>1032105</library_code>
				<library_code_original_value/>
				<secret_key/>
				<selected_patron_letters/>
				<selected_patron_letters_original_value/>
				<source_institution_id/>
				<source_institution_name/>
				<source_link_id/>
				<status>ACTIVE</status>
				<status_date>12/01/2016</status_date>
				<status_date_dummy>
					<calendar>12/01/2016</calendar>
					<calendar_ui/>
					<day>12</day>
					<day_ui/>
					<default_value_for_with_validation>1452609431219</default_value_for_with_validation>
					<full_date>2016-01-12</full_date>
					<input_date_tag_format>12.01.2016</input_date_tag_format>
					<month>0</month>
					<month_ui/>
					<date>false</date>
					<year>2016</year>
					<year_ui/>
				</status_date_dummy>
				<user_address_list>
					<user_address>
						<city>Oslo</city>
						<country>NOR</country>
						<create_date>12/01/2016</create_date>
						<entity_action/>
						<library_id/>
						<library_unit_id/>
						<line1>Grefsenkollveien 12 B</line1>
						<line2/>
						<line3/>
						<line4/>
						<line5/>
						<note/>
						<originating_id/>
						<postal_code>0490</postal_code>
						<preferred>true</preferred>
						<state_province/>
					</user_address>
				</user_address_list>
				<user_email_list>
					<user_email>
						<create_date>12/01/2016</create_date>
						<description/>
						<email>fredrik.h.juell@bi.no</email>
						<entity_action/>
						<external_id/>
						<library_id/>
						<library_unit_id/>
						<originating_id/>
						<preferred>true</preferred>
					</user_email>
				</user_email_list>
				<user_gender/>
				<user_group>1</user_group>
				<user_group_original_value/>
				<user_name>bi99999999</user_name>
				<user_phone_list>
					<user_phone>
						<create_date>12/01/2016</create_date>
						<entity_action/>
						<external_id/>
						<library_id/>
						<library_unit_id/>
						<originating_id/>
						<phone>95961616</phone>
						<preferred>true</preferred>
						<preferred_phone/>
						<preferred_sms/>
					</user_phone>
				</user_phone_list>
				<user_preferred_language>no</user_preferred_language>
				<user_preferred_language_original_value/>
				<user_record_type>PUBLIC</user_record_type>
				<user_status>ACTIVE</user_status>
				<user_title/>
				<user_title_original_value/>
				<user_type>INTEXTAUTH</user_type>
				<user_user_type>INTEXTAUTH</user_user_type>
				<user_web_address_list/>
				<web_site_url/>
			</user>
		</receiver>
		<sms_receiver>
			<attached_to_entity_id>702622300002215</attached_to_entity_id>
			<ftp_passive_mode>false</ftp_passive_mode>
			<ftp_server_name>sms.bibsys.no</ftp_server_name>
			<ftp_server_port>22</ftp_server_port>
			<ftp_server_secured>true</ftp_server_secured>
			<ftp_server_user_name>sms</ftp_server_user_name>
			<local_dir>/shared_app_storage/Alma_root//2200/2215/temp/external_systems/temp/</local_dir>
			<local_file_name>FulLostLoanLetter_20160626170040_175</local_file_name>
			<output_file_path>BI</output_file_path>
			<params/>
			<phone_list_str>95961616</phone_list_str>
			<preferred_language>no</preferred_language>
			<receiver_id/>
			<receiver_type/>
			<receiver_type_class>com.exlibris.core.infra.model.HFrUser</receiver_type_class>
			<sub_directory/>
			<target_file_name>FulLostLoanLetter_20160626170040_175</target_file_name>
		</sms_receiver>
	</receivers>
	<send_after_commit>true</send_after_commit>
	<throw_exceptions>false</throw_exceptions>
	<total_fines_amount>720.00</total_fines_amount>
	<user_for_printing>
		<address1>Grefsenkollveien 12 B</address1>
		<address2/>
		<address3/>
		<address4/>
		<address5/>
		<city>Oslo</city>
		<country>NOR</country>
		<email>fredrik.h.juell@bi.no</email>
		<identifiers>
			<code_value>
				<code>Primary Identifier</code>
				<value>bi99999999</value>
			</code_value>
		</identifiers>
		<name>Tonic, Gina</name>
		<phone>95961616</phone>
		<postal_code>0490</postal_code>
		<state/>
		<title/>
		<user_group>1</user_group>
		<user_title/>
	</user_for_printing>
</notification_data>